// <copyright file="SettingsData.cs" company="PublicDomain.is">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />

namespace PublicDomain
{
    // Directives
    using System.Collections.Generic;

    /// <summary>
    /// Urlister settings.
    /// </summary>
    public class SettingsData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PublicDomain.SettingsData"/> class.
        /// </summary>
        public SettingsData()
        {
            // Parameterless constructor
        }

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> always on top.
        /// </summary>
        /// <value><c>true</c> if always on top; otherwise, <c>false</c>.</value>
        public bool AlwaysOnTop { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> add checked.
        /// </summary>
        /// <value><c>true</c> if add checked; otherwise, <c>false</c>.</value>
        public bool AddChecked { get; set; } = true;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> check on click.
        /// </summary>
        /// <value><c>true</c> if check on click; otherwise, <c>false</c>.</value>
        public bool CheckOnClick { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> scan subdirectories.
        /// </summary>
        /// <value><c>true</c> if scan subdirectories; otherwise, <c>false</c>.</value>
        public bool ScanSubdirectories { get; set; } = true;

        /// <summary>
        /// Gets or sets the samples.
        /// </summary>
        /// <value>The samples.</value>
        public decimal Samples { get; set; } = 16;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> sequential save.
        /// </summary>
        /// <value><c>true</c> if sequential save; otherwise, <c>false</c>.</value>
        public bool SequentialSave { get; set; } = true;

        /// <summary>
        /// Gets or sets the file extensions.
        /// </summary>
        /// <value>The file extensions.</value>
        public string FileExtensions { get; set; } = "wav,flac,ogg,mp3";

        /// <summary>
        /// Gets or sets the samples directory.
        /// </summary>
        /// <value>The samples directory.</value>
        public string samplesDirectory { get; set; } = string.Empty;
    }
}